linters-settings:
  forbidigo:
    forbid:
      - .*\.Fatal.*
      - fmt\.Print.*

linters:
  enable-all: true

  disable:
    - depguard
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - gomnd
    - ireturn
    - varnamelen
    - tagalign
    - wastedassign

run:
  timeout: 10m
  tests: false
