-- +migrate Up

CREATE TABLE users (
    id UUID NOT NULL UNIQUE PRIMARY KEY,
    status VARCHAR(128) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE wallets (
    id UUID NOT NULL UNIQUE PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    name VARCHAR,
    currency VARCHAR NOT NULL,
    balance NUMERIC NOT NULL DEFAULT 0 CHECK ( balance >= 0 ),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- +migrate Down

DROP TABLE users CASCADE;