name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.23.2'
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v5
        with:
          version: v1.61.0
          args: --timeout=10m

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
          image: postgres:latest
          ports: ['5432:5432']
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          env:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: ${{secrets.DB_USERNAME}}
            POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
    env:
      DATABASE_URL: postgres://${{secrets.DB_USERNAME}}:${{secrets.DB_PASSWORD}}@localhost:5432/mydatabase
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.23.2'
      - uses: actions/checkout@v4
      - run: until pg_isready -h localhost -p 5432; do echo "Waiting for postgres..."; sleep 1; done
      - run: go test -race ./...

  build:
    strategy:
      matrix:
        go-version: [1.23.2]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: ${{matrix.go-version}}
      - uses: actions/checkout@v4
      - run: go build ./cmd/wallet-service