name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.22.4'
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v5
        with:
          version: v1.59.1
          args: --timeout=10m

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.22.4'
      - uses: actions/checkout@v4
      - run: go test -race ./...

  build:
    strategy:
      matrix:
        go-version: [1.22.4]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: ${{matrix.go-version}}
      - uses: actions/checkout@v4
      - run: go build ./cmd/wallet-service